services:
  api:
    build: .
    container_name: chiwi-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: chiwi-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: chiwi-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    build: .
    container_name: chiwi-worker
    env_file:
      - .env
    command: ["python", "-m", "src.worker"]
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    restart: unless-stopped
