# docker-compose.yaml

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-common: &common-config
  restart: unless-stopped
  logging: *default-logging
  env_file:
    - .env

services:
  mongo:
    image: mongo:8
    container_name: chiwi-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped
    logging: *default-logging

  redis:
    image: redis:8-alpine
    container_name: chiwi-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    logging: *default-logging

  api:
    <<: *common-config
    build: .
    image: nqh44/chiwi:local
    container_name: chiwi-api
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started

  worker:
    <<: *common-config
    build: .
    image: nqh44/chiwi:local
    container_name: chiwi-worker
    command: ["python", "-m", "src.worker"]
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started

  # Nginx Proxy cho Cloudflare
  nginx:
    image: nginx:alpine
    container_name: chiwi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api
    restart: unless-stopped
    logging: *default-logging

volumes:
  # redis_data: # Nếu bạn muốn giữ data redis khi restart
